services:
  # https://hub.docker.com/r/vaultwarden/server
  vaultwarden:
    container_name: vaultwarden
    image: "vaultwarden/server:${VAULTWARDEN_VERSION:-latest}"
    restart: unless-stopped
    #    ports:
    #      - target: 80
    #        published: ${VAULTWARDEN_PORT:-80}
    environment:
      DOMAIN: "https://${DOMAIN:-bitwarden.example.com}"
      ADMIN_TOKEN: "${ADMIN_TOKEN:-dn3ie9fCquu9QGHniD1KJ9EutvbLQoOh8Yei9MCrJgryOOk4tMXemKTMkC9fl2pz}"
    volumes:
      - type: bind
        source: ./volumes/vaultwarden/data
        target: /data
        bind:
          create_host_path: true
    networks:
      - sec

networks:
  sec:
    external: true
