# https://docs.gitlab.com/ee/install/docker/installation.html#install-gitlab-by-using-docker-compose
#
# Get initial root password:
#
# ```bash
# docker exec -it gitlab grep 'Password:' /etc/gitlab/initial_root_password
# ```
#
# Attention: The initial root password is only valid for 24 hours. Change it immediately.

services:
  # https://hub.docker.com/r/gitlab/gitlab-ce
  gitlab:
    container_name: gitlab
    image: "gitlab/gitlab-ce:${GITLAB_VERSION:-latest}"
    restart: unless-stopped
    ports:
      - target: 22
        published: ${GITLAB_SSH_PORT:-2424}
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url "https://gitlab.${DOMAIN:-example.com}"

        letsencrypt['enable'] = false

        nginx['enable'] = true
        nginx['listen_https'] = false
        nginx['listen_port'] = 80

        # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
        #  _____                                _____                                 #
        # |  __ \                              |  __ \                                #
        # | |__) |_____   _____ _ __ ___  ___  | |__) | __ _____  ___   _             #
        # |  _  // _ \ \ / / _ \ '__/ __|/ _ \ |  ___/ '__/ _ \ \/ / | | |            #
        # | | \ \  __/\ V /  __/ |  \__ \  __/ | |   | | | (_) >  <| |_| |            #
        # |_|  \_\___| \_/ \___|_|  |___/\___| |_|   |_|  \___/_/\_\\__, |            #
        #                                                            __/ |            #
        #                                                           |___/             #
        #                                                                             #
        # https://docs.gitlab.com/omnibus/settings/nginx.html                         #
        #                                                                             #
        # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

        nginx['real_ip_trusted_addresses'] = ['$DOCKER_PROXY_COMM_SUBNET']
        nginx['real_ip_header'] = 'X-Forwarded-For'
        nginx['real_ip_recursive'] = 'on'

        # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
        #   _____ _____ _    _                                                        #
        #  / ____/ ____| |  | |                                                       #
        # | (___| (___ | |__| |                                                       #
        #  \___ \\___ \|  __  |                                                       #
        #  ____) |___) | |  | |                                                       #
        # |_____/_____/|_|  |_|                                                       #
        #                                                                             #
        # https://docs.gitlab.com/ee/install/docker/configuration.html                #
        #                                                                             #
        # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

        gitlab_rails['gitlab_shell_ssh_port'] = ${GITLAB_SSH_PORT:-2424}

        # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
        #  _____            _     _                                                   #
        # |  __ \          (_)   | |                                                  #
        # | |__) |___  __ _ _ ___| |_ _ __ _   _                                      #
        # |  _  // _ \/ _` | / __| __| '__| | | |                                     #
        # | | \ \  __/ (_| | \__ \ |_| |  | |_| |                                     #
        # |_|  \_\___|\__, |_|___/\__|_|   \__, |                                     #
        #              __/ |                __/ |                                     #
        #             |___/                |___/                                      #
        #                                                                             #
        # https://docs.gitlab.com/ee/administration/packages/container_registry.html  #
        #                                                                             #
        # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

        registry_external_url "https://registry.${DOMAIN:-example.com}"

        registry['enable'] = true
        gitlab_rails['registry_enabled'] = true

        registry_nginx['enable'] = true
        registry_nginx['listen_https'] = false
        registry_nginx['listen_port'] = 5050

        # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
        #  _____                                                                        #
        # |  __ \                                                                       #
        # | |__) |_ _  __ _  ___  ___                                                   #
        # |  ___/ _` |/ _` |/ _ \/ __|                                                  #
        # | |  | (_| | (_| |  __/\__ \                                                  #
        # |_|   \__,_|\__, |\___||___/                                                  #
        #              __/ |                                                            #
        #             |___/                                                             #
        #                                                                               #
        # https://docs.gitlab.com/ee/administration/pages/                              #
        #                                                                               #
        # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

        pages_external_url "https://pages.${DOMAIN:-example.com}"

        gitlab_pages['enable'] = true
        gitlab_pages['listen_proxy'] = "0.0.0.0:8090"
        gitlab_pages['namespace_in_path'] = true
        gitlab_pages['status_uri'] = "/@status"

        pages_nginx['enable'] = true
        pages_nginx['listen_https'] = false

        # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
        #  _  __     _                          _                                       #
        # | |/ /    | |                        | |                                      #
        # | ' /_   _| |__   ___ _ __ _ __   ___| |_ ___  ___                            #
        # |  <| | | | '_ \ / _ \ '__| '_ \ / _ \ __/ _ \/ __|                           #
        # | . \ |_| | |_) |  __/ |  | | | |  __/ ||  __/\__ \                           #
        # |_|\_\__,_|_.__/ \___|_|  |_| |_|\___|\__\___||___/                           #
        #                                                                               #
        # https://docs.gitlab.com/ee/administration/clusters/kas.html                   #
        #                                                                               #
        # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

        gitlab_kas['enable'] = false

        # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
        #  _____                          _   _                                         #
        # |  __ \                        | | | |                                        #
        # | |__) | __ ___  _ __ ___   ___| |_| |__   ___ _   _ ___                      #
        # |  ___/ '__/ _ \| '_ ` _ \ / _ \ __| '_ \ / _ \ | | / __|                     #
        # | |   | | | (_) | | | | | |  __/ |_| | | |  __/ |_| \__ \                     #
        # |_|   |_|  \___/|_| |_| |_|\___|\__|_| |_|\___|\__,_|___/                     #
        #                                                                               #
        # https://docs.gitlab.com/ee/administration/monitoring/prometheus/              #
        #                                                                               #
        # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

        prometheus_monitoring['enable'] = false
        sidekiq['metrics_enabled'] = false
        puma['exporter_enabled'] = false
    shm_size: "256m"
    volumes:
      - type: bind
        source: ./volumes/gitlab/config
        target: /etc/gitlab
        bind:
          create_host_path: true
      - type: bind
        source: ./volumes/gitlab/logs
        target: /var/log/gitlab
        bind:
          create_host_path: true
      - type: bind
        source: ./volumes/gitlab/data
        target: /var/opt/gitlab
        bind:
          create_host_path: true
    networks:
      - dev

networks:
  dev:
    external: true
