# https://docs.gitea.com/installation/install-with-docker
#
# https://github.com/go-gitea/gitea/blob/main/custom/conf/app.example.ini

services:
  # https://hub.docker.com/r/gitea/gitea
  gitea:
    container_name: gitea
    image: "gitea/gitea:${GITEA_VERSION:-latest}"
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - target: 22
        published: "${GITEA_SSH_PORT:-2221}"
    environment:
      USER_UID: "${GITEA_PUID:-1000}"
      USER_GID: "${GITEA_PGID:-1000}"
      ## server
      GITEA__server__DOMAIN: "gitea.${DOMAIN:-example.com}"
      GITEA__server__SSH_DOMAIN: "gitea.${DOMAIN:-example.com}"
      GITEA__server__ROOT_URL: "https://gitea.${DOMAIN:-example.com}"
      GITEA__server__SSH_PORT: "${GITEA_SSH_PORT:-2221}"
      ## database
      GITEA__database__DB_TYPE: "postgres"
      GITEA__database__HOST: "postgres:5432"
      GITEA__database__NAME: "gitea"
      GITEA__database__USER: "gitea"
      GITEA__database__PASSWD: "${GITEA_DB_PASSWORD:?GITEA_DB_PASSWORD not set}"
      ## service
      GITEA__service__NO_REPLY_ADDRESS: "noreply.gitea.${DOMAIN:-example.com}"
      ## openid
      GITEA__openid__ENABLE_OPENID_SIGNIN: "false"
      GITEA__openid__ENABLE_OPENID_SIGNUP: "false"
    volumes:
      - type: bind
        source: ./volumes/gitea/data
        target: /data
        bind:
          create_host_path: true
      - type: bind
        source: /etc/timezone
        target: /etc/timezone
        read_only: true
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
    networks:
      - net
      - dev

  postgres:
    # https://hub.docker.com/_/postgres
    container_name: gitea_db
    image: "postgres:${GITEA_DB_VERSION:-latest}"
    restart: unless-stopped
    environment:
      POSTGRES_DB: "gitea"
      POSTGRES_USER: "gitea"
      POSTGRES_PASSWORD: "${GITEA_DB_PASSWORD:?GITEA_DB_PASSWORD not set}"
    volumes:
      - type: bind
        source: ./volumes/postgres/data
        target: /var/lib/postgresql/data
        bind:
          create_host_path: true
    networks:
      - net

networks:
  net:
    driver: bridge
  dev:
    external: true
