services:
  # https://hub.docker.com/r/stirlingtools/stirling-pdf
  stirling-pdf:
    container_name: stirling-pdf
    image: stirlingtools/stirling-pdf:${STIRLING_PDF_VERSION:-latest}
    restart: unless-stopped
    #    ports:
    #      - target: 8080
    #        published: ${STIRLING_PDF_PORT:-8080}
    environment:
      - DOCKER_ENABLE_SECURITY=${DOCKER_ENABLE_SECURITY:-false}
      - INSTALL_BOOK_AND_ADVANCED_HTML_OPS=${INSTALL_BOOK_AND_ADVANCED_HTML_OPS:-false}
      - LANGS=${LANGS:-de_DE}
    volumes:
      - type: bind
        source: ./volumes/stirling-pdf/trainingData
        target: /usr/share/tessdata
        bind:
          create_host_path: true
      - type: bind
        source: ./volumes/stirling-pdf/extraConfigs
        target: /configs
        bind:
          create_host_path: true
      - type: bind
        source: ./volumes/stirling-pdf/customFiles
        target: /customFiles
        bind:
          create_host_path: true
    #      - type: bind
    #        source: ./volumes/stirling-pdf/logs
    #        target: /logs
    #        bind:
    #          create_host_path: true
    networks:
      - proxy

networks:
  proxy:
    external: true
