# https://github.com/vineethmn/vaultwarden-docker-compose
# https://github.com/erkenes/docker-vaultwarden-server/tree/main

services:
  # https://hub.docker.com/r/vaultwarden/server
  vaultwarden:
    image: "vaultwarden/server:${VAULTWARDEN_VERSION:-latest}"
    container_name: vaultwarden
    restart: unless-stopped
    #    ports:
    #      - target: 80
    #        published: ${VAULTWARDEN_PORT:-80}
    environment:
      DOMAIN: "https://${DOMAIN:-bitwarden.local}"
      ADMIN_TOKEN: "${ADMIN_TOKEN:-dn3ie9fCquu9QGHniD1KJ9EutvbLQoOh8Yei9MCrJgryOOk4tMXemKTMkC9fl2pz}"
      WEBSOCKET_ENABLED: "${WEBSOCKET_ENABLED:-true}"
      REQUIRE_DEVICE_EMAIL: "${REQUIRE_DEVICE_EMAIL:-false}"

      # User permissions
      SIGNUPS_ALLOWED: "${SIGNUPS_ALLOWED:-true}"
      INVITATIONS_ALLOWED: "${INVITATIONS_ALLOWED:-false}"
      EMAIL_CHANGE_ALLOWED: "${EMAIL_CHANGE_ALLOWED:-true}"
      EMERGENCY_ACCESS_ALLOWED: "${EMERGENCY_ACCESS_ALLOWED:-true}"
      SENDS_ALLOWED: "${SENDS_ALLOWED:-true}"

      # Organisation
      ORG_EVENTS_ENABLED: "${ORG_EVENTS_ENABLED:-true}"
      ORG_GROUPS_ENABLED: "${ORG_GROUPS_ENABLED:-true}"

      # Logging
      LOG_FILE: "/data/vaultwarden.log"
      LOG_LEVEL: "${LOG_LEVEL:-warn}"
      USE_SYSLOG: "${USE_SYSLOG:-false}"
      EXTENDED_LOGGING: "${EXTENDED_LOGGING:-false}"
    volumes:
      - type: bind
        source: ./volumes/vaultwarden
        target: /data
        bind:
          create_host_path: true
    networks:
      - sec

networks:
  sec:
    external: true
