services:
  # https://hub.docker.com/r/linuxserver/heimdall/
  heimdall:
    container_name: heimdall
    image: "lscr.io/linuxserver/heimdall:${HEIMDALL_VERSION:-latest}"
    restart: unless-stopped
    ports:
      - target: 80
        published: ${HEIMDALL_PORT:-80}
        protocol: tcp
      - target: 443
        published: ${HEIMDALL_TLS_PORT:-443}
        protocol: tcp
    environment:
      PUID: "${HEIMDALL_PUID:-1000}"
      PGID: "${HEIMDALL_PGID:-1000}"
      TZ: "${TZ:-Europe/Berlin}"
    volumes:
      - type: bind
        source: ./volumes/heimdall/config
        target: /config
        bind:
          create_host_path: true

# Comment the following network section if you are not using a reverse proxy such as Nginx Proxy Manager
networks:
  proxy-network:
    external: true